docker build -t myapp .

docker run -d -p 8000:8000 myapp


# jknkjnknvmbmbmnbvmvvnngcghcvnvnbvnvnbvnvnggjyjfjhfgfffghffyyyyfvgnvnvncbf xfxxbbmhkkggvvmmkhkhjgjgv
# ghhghgghrydgffggjttughjgfhfhtthfhtyjyftyvngvgcfbcbcbcbbbfcbccbfcfbcbfkljlkjljhhjlkjlkjlkjlkjlkjkljkl
# jkljlkjkljkljlkjlkjlkjoijiojiojiojuihiuhjjknkjkkjnkjnkjntyguhgvyubhvuybinuybinybuin